. (Join-Path $PSScriptRoot '_Support.ps1')
$s=Read-T33PortugalSettings;Require-T33PortugalKeys;Assert-T33PortugalBaseline $s;$workspace=Assert-T33Workspace $s Integrated;Wait-T33Container (Get-T33OrchestratorContainer);Wait-T33Container 'tef-synthetic-data';$e=New-T33PortugalEvidence $s '20-integrated-workflow';Start-T33PortugalTranscript $e
try {
    $blueprintPath=Join-Path $workspace 'export\blueprint.json';$dockerInfoPath=Join-Path $workspace 'export\dockerinfo.json';if(-not(Test-Path $blueprintPath)-or -not(Test-Path $dockerInfoPath)){throw 'Exported integrated workflow definition is missing from the workspace.'}
    $workflowInput=ConvertTo-T33InlineReference @{file_path='/app/real_data.csv';max_rows=1000;rename_columns=@{datetime='timestamp'}}
    $request=@{blueprint=Get-Content $blueprintPath -Raw|ConvertFrom-Json;dockerinfo=Get-Content $dockerInfoPath -Raw|ConvertFrom-Json;inputs=@($workflowInput);services_api_key=$env:SERVICE_API_KEY}|ConvertTo-Json -Depth 100 -Compress
    $submitted=Invoke-T33PortugalWebRequest -Method Post -Uri "$($s.OrchestratorUrl)/workflows" -Headers (Get-T33BearerHeaders $env:ORCHESTRATOR_API_KEY) -Body $request;Save-T33Text (Join-Path $e 'submit-response.json') $submitted.Content;if($submitted.StatusCode -notin @(200,201,202)){throw "Workflow submission returned HTTP $($submitted.StatusCode)."}
    $workflowId=($submitted.Content|ConvertFrom-Json).workflow_id;if([string]::IsNullOrWhiteSpace($workflowId)){throw 'Workflow submission did not return workflow_id.'}
    $deadline=(Get-Date).AddMinutes(15);do {Start-Sleep -Seconds 5;$workflow=Invoke-T33PortugalWebRequest -Method Get -Uri "$($s.OrchestratorUrl)/workflows/$workflowId" -Headers (Get-T33BearerHeaders $env:ORCHESTRATOR_API_KEY);$tasks=Invoke-T33PortugalWebRequest -Method Get -Uri "$($s.OrchestratorUrl)/workflows/$workflowId/tasks" -Headers (Get-T33BearerHeaders $env:ORCHESTRATOR_API_KEY);Save-T33Text (Join-Path $e 'workflow.json') $workflow.Content;Save-T33Text (Join-Path $e 'tasks.json') $tasks.Content;$status=($workflow.Content|ConvertFrom-Json).status;Write-Host "$(Get-Date -Format o) workflow=$status"} while($status -notin @('complete','completed','failed') -and (Get-Date)-lt $deadline)
    ($tasks.Content|ConvertFrom-Json).tasks|Select-Object task_id,node_key,status,error|Format-Table -AutoSize
    if($status -in @('complete','completed')){Write-Host 'RESULT: PASS - the integrated Portugal workflow completed. Review saved outputs before judging data quality.'}elseif($status -eq 'failed'){Write-Host 'RESULT: RECORDED - integrated workflow failed. Saved task and workflow evidence; no source was changed.'}else{Write-Host 'RESULT: RECORDED - workflow did not reach a terminal state in 15 minutes. Saved evidence for investigation.'}
} finally {Stop-T33PortugalTranscript}
